- name: dnsmasq
  import_tasks: dnsmasq.yaml
  when:
    - ansible_distribution_version == '21.04'
    - inventory_hostname is match("hreidmarfrontend.*")
  tags: 
    - dnsmasq

- name: iptables
  import_tasks: iptables.yaml
  when:
    - ansible_distribution_version == '21.04'
    - inventory_hostname is match("hreidmarfrontend.*")
  tags: 
    - iptables